<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TwitterProxyWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/TwitterProxy/src/TwitterProxyWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TwitterProxy/src/TwitterProxyWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="PastebinProxyWSDLOperationRequest">
        <part name="msg" type="xsd:string"/>
    </message>
    <portType name="PastebinProxyWSDLPortType">
        <operation name="PastebinProxyWSDLOperation">
            <input name="input1" message="tns:PastebinProxyWSDLOperationRequest"/>
        </operation>
    </portType>
    <binding name="PastebinProxyWSDLBinding" type="tns:PastebinProxyWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="PastebinProxyWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TwitterProxy/src/TwitterProxyWSDL"/>
            </input>
        </operation>
    </binding>
    <service name="PastebinProxyWSDLService">
        <port name="PastebinProxyWSDLPort" binding="tns:PastebinProxyWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/TwitterProxyWSDLService/TwitterProxyWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="PastebinProxyWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="PastebinProxyWSDLPortTypeRole" portType="tns:PastebinProxyWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
